dataset:
  name: "CzechLynx_v2" # WildlifeReID-10k | CzechLynx_v2
  animal: "CzechLynx" # LeopardID2022 | ReunionTurtles| CzechLynx
  root: "/shared/sets/datasets/vision/czechlynx/${dataset.name}"
  metadata_file: "CzechLynxDataset-Metadata-Real.csv" # metadata/metadata_${dataset.animal}.csv | CzechLynxDataset-Metadata-Real.csv
  label_col: "unique_name" # identity | unique_name
  mask_col: "mask"
  no_background: false # false | true
  split_col: "split-time_closed" # split | split-time_closed
  train_split_value: "train"
  val_split_value: "test"

model:
  type: "megadescriptor"

train:
  seed: 0
  epochs: 30
  batch_size: 16
  num_workers: 8
  accumulation_steps: 4
  lr: 0.0001
  weight_decay: 0.0
  amp: "false"           # auto | true | false
  deterministic: false
  resume_checkpoint: null
  log_every: 5

loss:
  margin: 0.25
  scale: 16.0

scheduler:
  type: "cosine"
  eta_min_scale: 1e-3

output:
  run_dir: "results/${dataset.name}/${dataset.animal}/mask_${dataset.no_background}"
  save_every: 10
  save_best: true
  best_metric: "top_1"
  csv_path: "results/${dataset.name}/${dataset.animal}/mask_${dataset.no_background}/train_metrics.csv"

benchmark:
  top_k: [1, 5, 10]
  compute_map: true
  val_batch_size: 32
  val_num_workers: 8

safety_checks:
  enabled: true

wandb:
  enabled: false
  project: "explainable-reid"
  entity: null
  group: null
  tags: []
  name: null
